package fr.robie.craftengineconverter.converter.bedrock;

import com.google.gson.JsonObject;
import fr.robie.craftengineconverter.api.configuration.bedrock.ItemTextureConfiguration;
import fr.robie.craftengineconverter.api.configuration.bedrock.ManifestConfiguration;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.MappingsConfiguration;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.block.BlockMappingConfiguration;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.item.GroupDefinitionMapping;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.item.ItemMapping;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.item.ItemModelItemMapping;
import fr.robie.craftengineconverter.api.configuration.bedrock.mapping.item.option.BedrockOptions;
import fr.robie.craftengineconverter.api.configuration.bedrock.texture.FlipbookTextureConfiguration;
import fr.robie.craftengineconverter.api.configuration.bedrock.texture.TextureData;
import fr.robie.craftengineconverter.api.manager.FileCacheManager;
import fr.robie.craftengineconverter.converter.bedrock.animation.BedrockAnimation;
import fr.robie.craftengineconverter.converter.bedrock.animation.BedrockAnimationController;
import fr.robie.craftengineconverter.converter.bedrock.animation.BedrockRenderControllers;
import fr.robie.craftengineconverter.converter.bedrock.attachable.BedrockAttachableContext;
import fr.robie.craftengineconverter.converter.bedrock.block.BedrockBlockMapper;
import fr.robie.craftengineconverter.converter.bedrock.geometry.BedrockGeometry;
import fr.robie.craftengineconverter.converter.bedrock.lang.LanguageMapper;
import fr.robie.craftengineconverter.converter.bedrock.geometry.GeometryMapper;
import fr.robie.craftengineconverter.converter.bedrock.geometry.JavaBlockModel;
import fr.robie.craftengineconverter.converter.bedrock.sound.SoundMapper;
import fr.robie.craftengineconverter.converter.bedrock.texture.CachedTextureInfo;
import fr.robie.craftengineconverter.converter.bedrock.texture.TexturePipeline;
import org.bukkit.Material;

import java.io.File;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public class ConversionContext {
    private final MappingsConfiguration mappings = new MappingsConfiguration();
    private final ItemTextureConfiguration texturesConfig = new ItemTextureConfiguration();
    private final ItemTextureConfiguration terrainTexturesConfig = new ItemTextureConfiguration();
    private final FlipbookTextureConfiguration flipbookConfig = new FlipbookTextureConfiguration();
    private final BlockMappingConfiguration blockMappings = new BlockMappingConfiguration();
    private final TexturePipeline texturePipeline = new TexturePipeline();
    private final Map<String, BedrockGeometry> collectedGeometry = new HashMap<>();
    private final Map<String, Object> collectedAttachables = new HashMap<>();
    private final Map<String, BedrockRenderControllers> renderControllers = new HashMap<>();
    private final Map<String, BedrockAnimation> animations = new HashMap<>();
    private final Map<String, BedrockAnimationController> animationControllers = new HashMap<>();
    private final SoundMapper soundMapper = new SoundMapper();
    private final LanguageMapper languageMapper = new LanguageMapper();
    private ManifestConfiguration manifest;
    private final Path customMappingsDir;
    private final Path texturesDir;
    private final Path packDir;
    private Path javaAssetsDir;

    public ConversionContext(Path customMappingsDir, Path texturesDir, Path packDir) {
        this.customMappingsDir = customMappingsDir;
        this.texturesDir = texturesDir;
        this.packDir = packDir;
        this.manifest = new ManifestConfiguration("CraftEngineConverter Pack")
                .setPackDescription("Generated by CraftEngineConverter")
                .setPackUUID(java.util.UUID.randomUUID())
                .setPackVersion(1, 0, 0)
                .setMinEngineVersion(1, 21, 0);
        this.texturesConfig.setResourcePackName("CraftEngineConverter")
                .setTextureName("atlas.items");
        this.terrainTexturesConfig.setResourcePackName("CraftEngineConverter")
                .setTextureName("atlas.terrain")
                .setFileName("terrain_texture.json");
    }

    public ConversionContext withJavaAssetsDir(Path javaAssetsDir) {
        this.javaAssetsDir = javaAssetsDir;
        return this;
    }

    public ConversionContext withManifest(ManifestConfiguration manifest) {
        if (manifest != null) this.manifest = manifest;
        return this;
    }

    public ManifestConfiguration getManifest() {
        return this.manifest;
    }

    public MappingsConfiguration mappings() {
        return this.mappings;
    }

    public ItemTextureConfiguration textures() {
        return this.texturesConfig;
    }

    public ItemTextureConfiguration terrainTextures() {
        return this.terrainTexturesConfig;
    }

    public TexturePipeline texturePipeline() {
        return this.texturePipeline;
    }

    public Path customMappingsDir() {
        return this.customMappingsDir;
    }

    public Path texturesDir() {
        return this.texturesDir;
    }

    public Path packDir() {
        return this.packDir;
    }

    public Path javaAssetsDir() {
        return this.javaAssetsDir;
    }

    public Map<String, BedrockGeometry> collectedGeometry() {
        return this.collectedGeometry;
    }

    public Map<String, Object> collectedAttachables() {
        return this.collectedAttachables;
    }

    public void acceptMapping(ItemMapping mapping) {
        if (mapping == null) return;

        if (mapping instanceof GroupDefinitionMapping newGroup && newGroup.getModel() != null) {
            String model = newGroup.getModel();
            Material mat = mapping.getJavaMaterial();
            List<ItemMapping> existing = this.mappings.getMappings(mat);
            if (existing != null) {
                for (ItemMapping existingMapping : existing) {
                    if (existingMapping instanceof GroupDefinitionMapping existingGroup
                            && model.equals(existingGroup.getModel())
                            && existingMapping != mapping) {
                        for (ItemMapping def : newGroup.getDefinitions()) {
                            existingGroup.addDefinition(def);
                        }
                        return;
                    }
                }
            }
        } else if (mapping instanceof ItemModelItemMapping single && single.getBedrockModelPath() != null) {
            String model = single.getBedrockModelPath();
            Material mat = mapping.getJavaMaterial();
            List<ItemMapping> existing = this.mappings.getMappings(mat);
            if (existing != null) {
                for (ItemMapping existingMapping : existing) {
                    if (existingMapping instanceof GroupDefinitionMapping existingGroup
                            && model.equals(existingGroup.getModel())) {
                        existingGroup.addDefinition(single);
                        return;
                    }
                }
                for (ItemMapping existingMapping : existing) {
                    if (existingMapping instanceof ItemModelItemMapping existingSingle
                            && existingSingle != mapping
                            && model.equals(existingSingle.getBedrockModelPath())) {
                        GroupDefinitionMapping group = new GroupDefinitionMapping(mat, existingSingle.getBedrockIdentifier());
                        group.setModel(model);
                        group.addDefinition(existingSingle);
                        group.addDefinition(single);
                        this.mappings.replaceItemMapping(mat, existingMapping, group);
                        return;
                    }
                }
            }
        }

        this.mappings.addItemMapping(mapping);

        if (!mapping.getTexturesData().isEmpty()) {
            TextureData firstTd = mapping.getTexturesData().getFirst();
            if (!firstTd.getTextures().isEmpty()) {
                String firstTex = firstTd.getTextures().getFirst();
                String iconTex;
                if (firstTex.matches(".*_\\d+$")) {
                    iconTex = firstTex.replaceAll("_\\d+$", "_icon");
                } else {
                    iconTex = firstTex + "_icon";
                }

                String iconId = mapping.getBedrockIdentifier() + "_icon";
                TextureData iconTd = new TextureData(iconId);
                iconTd.addTexture(iconTex);
                this.texturesConfig.addTextureData(iconTd);

                try {
                    Path srcPng = this.texturesDir.resolve(firstTex.substring("textures/".length()) + ".png");
                    Path dstPng = this.texturesDir.resolve(iconTex.substring("textures/".length()) + ".png");
                    java.nio.file.Files.createDirectories(dstPng.getParent());
                    java.nio.file.Files.copy(srcPng, dstPng, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                } catch (Exception e) {
                    fr.robie.messageflow.logger.Logger.warn("Could not copy icon texture: " + e.getMessage());
                }

                BedrockOptions opts = mapping.getBedrockOptions();
                if (opts == null) {
                    opts = new BedrockOptions();
                }
                opts.setIcon(iconTd.getBedrockIdentifier());
                mapping.setBedrockOptions(opts);
            }
        }
    }

    public void registerRenderController(String key, BedrockRenderControllers rc) {
        if (!rc.isEmpty()) {
            this.renderControllers.put(key, rc);
        }
    }

    public void registerAnimation(String key, BedrockAnimation anim) {
        if (!anim.isEmpty()) {
            this.animations.put(key, anim);
        }
    }

    public void registerAnimationController(String key, BedrockAnimationController ac) {
        if (!ac.isEmpty()) {
            this.animationControllers.put(key, ac);
        }
    }

    public void registerAttachable(String bedrockKey, BedrockAttachableContext ctx) {
        if (!ctx.isEmpty()) {
            this.collectedAttachables.put(bedrockKey, ctx);
        }
    }

    public BlockMappingConfiguration blockMappings() {
        return this.blockMappings;
    }

    public void addLangDirectory(File langDir, String namespace) {
        this.languageMapper.addFromLangDirectory(langDir, namespace);
    }

    public void convertSoundDefinitions(File javaSoundsJson, String namespace) {
        if (this.javaAssetsDir == null) return;
        fr.robie.craftengineconverter.api.manager.FileCacheManager.getJsonCache()
                .getData(javaSoundsJson.toPath())
                .ifPresent(root -> this.soundMapper.addFromJavaSounds(
                        root, namespace, this.javaAssetsDir, this.packDir.resolve("sounds")));
    }

    public void convertBlocks() {
        if (this.javaAssetsDir == null) return;
        BedrockBlockMapper mapper = new BedrockBlockMapper(this.javaAssetsDir);
        mapper.mapAllBlocks();
        BlockMappingConfiguration result = mapper.result();
        if (!result.isEmpty()) {
            for (var entry : result.entries().entrySet()) {
                this.blockMappings.mapBlock(entry.getKey(), entry.getValue());
            }
            fr.robie.messageflow.logger.Logger.info("Mapped " + result.size() + " block states");
        }
    }

    public void registerTextureData(String modelPath, String bedrockKey) {
        this.registerTextureDataInternal(modelPath, bedrockKey, this.texturesConfig);
    }

    public void copyTexture(String modelPath, String bedrockKey) {
        if (this.javaAssetsDir == null) return;
        Optional<CachedTextureInfo> resolved = this.texturePipeline.resolveTexture(modelPath, bedrockKey, this.javaAssetsDir);
        if (resolved.isEmpty()) {
            resolved = this.tryResolveTextureFromModel(modelPath, bedrockKey);
        }
        resolved.ifPresent(info -> this.texturePipeline.copyTexture(info, this.texturesDir));
    }

    public void registerTextureDataAsTerrain(String modelPath, String bedrockKey) {
        this.registerTextureDataInternal(modelPath, bedrockKey, this.terrainTexturesConfig);
    }

    private void registerTextureDataInternal(String modelPath, String bedrockKey, ItemTextureConfiguration targetConfig) {
        if (this.javaAssetsDir == null) return;
        Optional<CachedTextureInfo> resolved = this.texturePipeline.resolveTexture(modelPath, bedrockKey, this.javaAssetsDir);
        if (resolved.isEmpty()) {
            resolved = this.tryResolveTextureFromModel(modelPath, bedrockKey);
        }
        resolved.ifPresent(info -> {
            this.texturePipeline.copyTexture(info, this.texturesDir);
            TextureData td = this.texturePipeline.toTextureData(info);
            targetConfig.addTextureData(td);
        });
    }

    private Optional<CachedTextureInfo> tryResolveTextureFromModel(String modelPath, String bedrockKey) {
        try {
            String[] parts = modelPath.split(":", 2);
            String ns = parts.length > 1 ? parts[0] : "minecraft";
            String path = parts.length > 1 ? parts[1] : parts[0];
            Path modelFile = this.javaAssetsDir.resolve(ns + "/models/" + path + ".json");
            if (!modelFile.toFile().exists()) return Optional.empty();

            JavaBlockModel model = JavaBlockModel.load(modelFile);
            this.resolveParentTextures(model, new java.util.HashSet<>());

            for (var tex : model.textures().values()) {
                if (tex.startsWith("#") || tex.startsWith("minecraft:")) continue;
                String fallbackModelPath = ns + ":" + tex;
                Optional<CachedTextureInfo> result = this.texturePipeline.resolveTexture(fallbackModelPath, bedrockKey, this.javaAssetsDir);
                if (result.isPresent()) return result;
            }
        } catch (Exception e) {
            fr.robie.messageflow.logger.Logger.warn("Failed to resolve texture from model for " + modelPath);
        }
        return Optional.empty();
    }

    private void resolveParentTextures(JavaBlockModel model, java.util.Set<String> visited) {
        if (model.parent().isEmpty() || !visited.add(model.parent().get())) return;
        String parentPath = model.parent().get();
        String[] pParts = parentPath.split(":", 2);
        String pNs = pParts.length > 1 ? pParts[0] : "minecraft";
        String pPath = pParts.length > 1 ? pParts[1] : pParts[0];
        Path parentFile = this.javaAssetsDir.resolve(pNs + "/models/" + pPath + ".json");
        if (!parentFile.toFile().exists()) return;

        try {
            JavaBlockModel parent = JavaBlockModel.load(parentFile);
            this.resolveParentTextures(parent, visited);
            // Inherit unresolved textures from parent
            for (var entry : parent.textures().entrySet()) {
                if (!model.textures().containsKey(entry.getKey())) {
                    String val = entry.getValue();
                    if (val.startsWith("#") && model.textures().containsKey(val.substring(1))) {
                        model.textures().put(entry.getKey(), model.textures().get(val.substring(1)));
                    } else {
                        model.textures().put(entry.getKey(), val);
                    }
                }
            }
        } catch (Exception ignored) {}
    }

    public void registerGeometry(String modelPath, String bedrockKey, int texW, int texH) {
        if (this.javaAssetsDir == null) return;
        String[] parts = modelPath.split(":", 2);
        String namespace = parts.length > 1 ? parts[0] : "minecraft";
        String path = parts.length > 1 ? parts[1] : parts[0];
        Path modelFile = this.javaAssetsDir.resolve(namespace + "/models/" + path + ".json");
        if (!modelFile.toFile().exists()) return;

        try {
            JavaBlockModel javaModel = JavaBlockModel.load(modelFile);
            GeometryMapper mapper = new GeometryMapper();
            String safeKey = bedrockKey.replace(":", ".").replace("/", "_");
            BedrockGeometry geo = mapper.mapGeometry(safeKey, javaModel, texW, texH);
            this.collectedGeometry.put(bedrockKey, geo);
        } catch (Exception e) {
            fr.robie.messageflow.logger.Logger.error("Failed to map geometry for " + modelPath, e);
        }
    }

    public void saveAll() {
        this.mappings.saveMappings(this.customMappingsDir);
        this.texturesConfig.save(this.texturesDir);
        if (!this.terrainTexturesConfig.isEmpty()) {
            this.terrainTexturesConfig.save(this.texturesDir);
        }
        if (!this.flipbookConfig.isEmpty()) {
            this.flipbookConfig.save(this.texturesDir);
        }
        this.blockMappings.save(this.customMappingsDir);

        this.languageMapper.save(this.packDir.resolve("texts"));

        if (!this.soundMapper.isEmpty()) {
            try {
                Path soundDefPath = this.packDir.resolve("sounds/sound_definitions.json");
                java.nio.file.Files.createDirectories(soundDefPath.getParent());
                fr.robie.craftengineconverter.api.manager.FileCacheManager.saveJsonToFile(soundDefPath, this.soundMapper.serialize());
                fr.robie.messageflow.logger.Logger.info("Saved " + this.soundMapper.size() + " sound definitions");
            } catch (Exception e) {
                fr.robie.messageflow.logger.Logger.error("Failed to save sound definitions", e);
            }
        }

        if (this.manifest != null) {
            this.manifest.saveManifest(this.packDir);
        }

        Path geoDir = this.packDir.resolve("models/entity");
        for (Map.Entry<String, BedrockGeometry> entry : this.collectedGeometry.entrySet()) {
            try {
                java.nio.file.Files.createDirectories(geoDir);
                JsonObject json = entry.getValue().serialize();
                String fileName = "geometry." + entry.getKey().replace(":", ".") + ".geo.json";
                Path outPath = geoDir.resolve(fileName);
                FileCacheManager.saveJsonToFile(outPath, json);
            } catch (Exception e) {
                fr.robie.messageflow.logger.Logger.error("Failed to save geometry for " + entry.getKey(), e);
            }
        }

        Path animDir = this.packDir.resolve("animations");
        for (Map.Entry<String, BedrockAnimation> entry : this.animations.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                try {
                    java.nio.file.Files.createDirectories(animDir);
                    JsonObject json = entry.getValue().serialize();
                    String fileName = entry.getKey().replace(":", ".").replace("/", "_") + ".animation.json";
                    Path outPath = animDir.resolve(fileName);
                    FileCacheManager.saveJsonToFile(outPath, json);
                } catch (Exception e) {
                    fr.robie.messageflow.logger.Logger.error("Failed to save animation for " + entry.getKey(), e);
                }
            }
        }

        Path acDir = this.packDir.resolve("animation_controllers");
        for (Map.Entry<String, BedrockAnimationController> entry : this.animationControllers.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                try {
                    java.nio.file.Files.createDirectories(acDir);
                    JsonObject json = entry.getValue().serialize();
                    String fileName = entry.getKey().replace(":", ".").replace("/", "_") + ".animation_controllers.json";
                    Path outPath = acDir.resolve(fileName);
                    FileCacheManager.saveJsonToFile(outPath, json);
                } catch (Exception e) {
                    fr.robie.messageflow.logger.Logger.error("Failed to save animation controller for " + entry.getKey(), e);
                }
            }
        }

        Path rcDir = this.packDir.resolve("render_controllers");
        for (Map.Entry<String, BedrockRenderControllers> entry : this.renderControllers.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                try {
                    java.nio.file.Files.createDirectories(rcDir);
                    JsonObject json = entry.getValue().serialize();
                    String fileName = entry.getKey().replace(":", ".").replace("/", "_") + ".render_controllers.json";
                    Path outPath = rcDir.resolve(fileName);
                    FileCacheManager.saveJsonToFile(outPath, json);
                } catch (Exception e) {
                    fr.robie.messageflow.logger.Logger.error("Failed to save render controllers for " + entry.getKey(), e);
                }
            }
        }

        Path attachDir = this.packDir.resolve("attachables");
        for (Map.Entry<String, Object> entry : this.collectedAttachables.entrySet()) {
            if (entry.getValue() instanceof BedrockAttachableContext actx) {
                actx.attachable().ifPresent(att -> {
                    try {
                        java.nio.file.Files.createDirectories(attachDir);
                        JsonObject json = att.serialize();
                        String fileName = entry.getKey().replace(":", ".").replace("/", "_") + ".json";
                        Path outPath = attachDir.resolve(fileName);
                        FileCacheManager.saveJsonToFile(outPath, json);
                    } catch (Exception e) {
                        fr.robie.messageflow.logger.Logger.error("Failed to save attachable for " + entry.getKey(), e);
                    }
                });
            }
        }
    }

    private static void writeDefaultPackIcon(java.nio.file.Path dest) throws java.io.IOException {
        java.awt.image.BufferedImage img = new java.awt.image.BufferedImage(256, 256, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D g = img.createGraphics();
        g.setColor(new java.awt.Color(66, 135, 245));
        g.fillRect(0, 0, 256, 256);
        g.setColor(java.awt.Color.WHITE);
        g.setFont(g.getFont().deriveFont(java.awt.Font.BOLD, 48));
        String label = "CEC";
        java.awt.FontMetrics fm = g.getFontMetrics();
        int x = (256 - fm.stringWidth(label)) / 2;
        int y = ((256 - fm.getHeight()) / 2) + fm.getAscent();
        g.drawString(label, x, y);
        g.dispose();
        javax.imageio.ImageIO.write(img, "PNG", dest.toFile());
    }
}
